# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'details_gui1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(838, 700)
        
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(10, 470, 411, 221))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 409, 219))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_4)
        
        self.l_poster = QtWidgets.QLabel(Dialog)
        self.l_poster.setGeometry(QtCore.QRect(20, 10, 291, 441))
        self.l_poster.setObjectName("l_poster")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(340, 430, 71, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.hl_screenshot = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_4)
        self.hl_screenshot.setContentsMargins(0, 0, 0, 0)
        self.hl_screenshot.setObjectName("hl_screenshot")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(340, 20, 71, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vl_labels = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vl_labels.setContentsMargins(0, 0, 0, 0)
        self.vl_labels.setObjectName("vl_labels")
        self.l_name = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.l_name.setObjectName("l_name")
        self.vl_labels.addWidget(self.l_name)
        self.l_version = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.l_version.setObjectName("l_version")
        self.vl_labels.addWidget(self.l_version)
        self.l_category = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.l_category.setObjectName("l_category")
        self.vl_labels.addWidget(self.l_category)
        self.l_update = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.l_update.setObjectName("l_update")
        self.vl_labels.addWidget(self.l_update)
        self.l_playstore = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.l_playstore.setObjectName("l_playstore")
        self.vl_labels.addWidget(self.l_playstore)
        self.l_developer = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.l_developer.setObjectName("l_developer")
        self.vl_labels.addWidget(self.l_developer)
        self.l_requirements = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.l_requirements.setObjectName("l_requirements")
        self.vl_labels.addWidget(self.l_requirements)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(410, 20, 16, 151))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.vl_separates = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.vl_separates.setContentsMargins(0, 0, 0, 0)
        self.vl_separates.setObjectName("vl_separates")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.vl_separates.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.vl_separates.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.vl_separates.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.vl_separates.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.vl_separates.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.vl_separates.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.vl_separates.addWidget(self.label_14)
        self.l_description = QtWidgets.QLabel(Dialog)
        self.l_description.setGeometry(QtCore.QRect(340, 180, 81, 16))
        self.l_description.setObjectName("l_description")
        self.l_whatnew = QtWidgets.QLabel(Dialog)
        self.l_whatnew.setGeometry(QtCore.QRect(340, 250, 81, 16))
        self.l_whatnew.setObjectName("l_whatnew")
        self.l_features = QtWidgets.QLabel(Dialog)
        self.l_features.setGeometry(QtCore.QRect(340, 330, 81, 16))
        self.l_features.setObjectName("l_features")
        self.l_function = QtWidgets.QLabel(Dialog)
        self.l_function.setGeometry(QtCore.QRect(340, 390, 81, 16))
        self.l_function.setObjectName("l_function")
        self.e_description = QtWidgets.QTextEdit(Dialog)
        self.e_description.setGeometry(QtCore.QRect(420, 180, 401, 61))
        self.e_description.setObjectName("e_description")
        self.e_whatsnew = QtWidgets.QTextEdit(Dialog)
        self.e_whatsnew.setGeometry(QtCore.QRect(420, 250, 401, 71))
        self.e_whatsnew.setObjectName("e_whatsnew")
        self.e_features = QtWidgets.QTextEdit(Dialog)
        self.e_features.setGeometry(QtCore.QRect(420, 330, 401, 51))
        self.e_features.setObjectName("e_features")
        self.e_function = QtWidgets.QTextEdit(Dialog)
        self.e_function.setGeometry(QtCore.QRect(420, 390, 401, 71))
        self.e_function.setObjectName("e_function")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(430, 20, 391, 151))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.vl_content = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.vl_content.setContentsMargins(0, 0, 0, 0)
        self.vl_content.setObjectName("vl_content")
        self.c_name = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.c_name.setObjectName("c_name")
        self.vl_content.addWidget(self.c_name)
        self.c_version = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.c_version.setObjectName("c_version")
        self.vl_content.addWidget(self.c_version)
        self.c_category = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.c_category.setObjectName("c_category")
        self.vl_content.addWidget(self.c_category)
        self.c_update = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.c_update.setObjectName("c_update")
        self.vl_content.addWidget(self.c_update)
        self.c_playstore = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.c_playstore.setObjectName("c_playstore")
        self.vl_content.addWidget(self.c_playstore)
        self.c_developer = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.c_developer.setObjectName("c_developer")
        self.vl_content.addWidget(self.c_developer)
        self.c_requirements = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.c_requirements.setObjectName("c_requirements")
        self.vl_content.addWidget(self.c_requirements)
        self.e_modinfo = QtWidgets.QTextEdit(Dialog)
        self.e_modinfo.setGeometry(QtCore.QRect(610, 490, 211, 91))
        self.e_modinfo.setObjectName("e_modinfo")
        self.l_modinfo = QtWidgets.QLabel(Dialog)
        self.l_modinfo.setGeometry(QtCore.QRect(610, 470, 71, 16))
        self.l_modinfo.setObjectName("l_modinfo")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(610, 590, 211, 101))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.vl_download = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.vl_download.setContentsMargins(0, 0, 0, 0)
        self.vl_download.setObjectName("vl_download")
        self.l_next = QtWidgets.QLabel(Dialog)
        self.l_next.setGeometry(QtCore.QRect(770, 470, 47, 13))
        self.l_next.setObjectName("l_next")
        self.l_previous = QtWidgets.QLabel(Dialog)
        self.l_previous.setGeometry(QtCore.QRect(700, 470, 47, 13))
        self.l_previous.setObjectName("l_previous")
 
        self.scrollArea2 = QtWidgets.QScrollArea(Dialog)
        self.scrollArea2.setGeometry(QtCore.QRect(430, 470, 171, 221))
        self.scrollArea2.setWidgetResizable(True)
        self.scrollArea2.setObjectName("scrollArea2")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 169, 219))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.scrollArea2.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(340, 450, 71, 16))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.hl_related = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.hl_related.setContentsMargins(0, 0, 0, 0)
        self.hl_related.setObjectName("hl_related")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Details"))
        self.l_poster.setText(_translate("Dialog", "POSTER"))
        self.l_name.setText(_translate("Dialog", "Name"))
        self.l_version.setText(_translate("Dialog", "Version"))
        self.l_category.setText(_translate("Dialog", "Category"))
        self.l_update.setText(_translate("Dialog", "Updated"))
        self.l_playstore.setText(_translate("Dialog", "Playstore"))
        self.l_developer.setText(_translate("Dialog", "Developer"))
        self.l_requirements.setText(_translate("Dialog", "Requirements"))
        self.label_8.setText(_translate("Dialog", ":"))
        self.label_9.setText(_translate("Dialog", ":"))
        self.label_10.setText(_translate("Dialog", ":"))
        self.label_11.setText(_translate("Dialog", ":"))
        self.label_12.setText(_translate("Dialog", ":"))
        self.label_13.setText(_translate("Dialog", ":"))
        self.label_14.setText(_translate("Dialog", ":"))
        self.l_description.setText(_translate("Dialog", "Description     :"))
        self.l_whatnew.setText(_translate("Dialog", "What\'s New    :"))
        self.l_features.setText(_translate("Dialog", "Features         :"))
        self.l_function.setText(_translate("Dialog", "Function         :"))
        self.c_name.setText(_translate("Dialog", "Name"))
        self.c_version.setText(_translate("Dialog", "Version"))
        self.c_category.setText(_translate("Dialog", "Category"))
        self.c_update.setText(_translate("Dialog", "Updated"))
        self.c_playstore.setText(_translate("Dialog", "Playstore"))
        self.c_developer.setText(_translate("Dialog", "Developer"))
        self.c_requirements.setText(_translate("Dialog", "Requirements"))
        self.l_modinfo.setText(_translate("Dialog", "Mod Info :"))
        self.l_next.setText(_translate("Dialog", "Next"))
        self.l_previous.setText(_translate("Dialog", "Previous"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

